---
title: "Projeto Extração de dados de PDF"
output: html_notebook
---

Bibliotecas e o Arquivos que iremos usar

```{r include=FALSE}
library(tabulapdf)
library(tidyr)
library(dplyr)
dadosLista <- extract_tables(file = "arquivos/LR_017_Relatório_Cotacões_de_Referencias_30_8_2024.pdf")
```

Variaveis Globais

```{r include=FALSE}
q = 0
iLinhas = 0
df2=data.frame()
df1=data.frame()
df= data.frame()
```

Tratamento de dados

```{r include=FALSE}
while (q < length(dadosLista)) {
  q = q + 1
  iLinhas = iLinhas + length(dadosLista[[q]][[1]])
  if ((length(dadosLista[[q]])) > 8){ 
    df1 = data.frame(dadosLista[q]) 
    df1 = df1 %>% unite(col = ...1,1:2)
    df = bind_rows(df,df1)

  } else {
    df2 = dadosLista[[q]] 
    df = bind_rows(df,df2)
    
  }
}
colnames(df)[1] <- "Produtos"
colnames(df)[2] <- "Tipo"
colnames(df)[3] <- "Origem"
colnames(df)[4] <- "Embalagem"
colnames(df)[5] <- "KG"
colnames(df)[6] <- "Minimo"
colnames(df)[7] <- "Preco"
colnames(df)[8] <- "Comum"

  dadosTratados = df %>% filter(Produtos != 'NA') %>% filter (Preco != 'NA') %>%  filter(Tipo != 'NA')

```


```{r include=FALSE}
  
```
